### PR TITLE
update POST to server created slug

### PR DESCRIPTION
**Pull request by bourgeoa**
I have implemented :
- POST with slug server created when resource exists. it uses like NSS uuid.V1
- to check the result `I have added a header slug` (it only a way to find the slug created by the server may be deleted)
- added tests
- I have renamed back `deleteDir` to `deleteContainer` and `deleteFile` to deleteResource

For my own help I have created a cheat sheet.md to check solid-rest compared to NSS spec implementation.

### CODE REVIEW

**Comment by jeff-zucker** [comment]
Please pull the existing master before submitting a PR. 

> to check the result I have added a header slug (it only a way to find the slug created by the server may be deleted)

I do not understand this at all.  A POST has to return the new file location in the location header of the response.  Why is a slug header needed?   Does this slug header exist in NSS?

**Comment by jeff-zucker** [comment]
What is the source of the cheatsheet?  Is it based on something that NSS uses?

**Comment by bourgeoa** [comment]
I checked there was no new commit and it was not enough. I shall go to New branches

The header slug is an artefact for the tests. I did not find a way to find the name of the resource created.
Have you any suggestion ?

**Comment by bourgeoa** [comment]
The cheat cheep should not be kept. It to support discussion.
I should put it in an issue if you agree

Where does it come from ?
 It is the result of my understanding from NSS code, consensus on on going spec ( atomic delete) and rising issue ( avoid multiple URL for a resource )

**Comment by jeff-zucker** [comment]
Am I correct that this PR #37 was replaced with PR #38 which is now merged?  I run 23 tests now and all pass. Thanks so much for your work.  If you haven't checked the chat room I have a message for you there.

**Pull request closed without merging**
