### PR TITLE
Windows Friendly Paths

### PR DESCRIPTION
**Pull request by CxRes**
I am just putting this change out there (crossing it off my list as it were).  

No hurry though... It can wait till you get better!

### CODE REVIEW

**Comment by CxRes** [comment]
Sorry, I have piled on the changes since I opened this PR. Hopefully this would be the last of it.

You may want to consider doing a squash merge when you get to it!!!!!

**Comment by jeff-zucker** [comment]
OK, I made too many changes in my solid-rest to merge yours so I put all of your changes in by hand.  I have solid-auth-cli under Travis now and it gave me 17/19 in app and 19/19 in file tests on Windows and 19/19 on both everywhere else.  After implementing your changes in this PR the app tests improved to 19/19 but the file test in Windows dropped to 4/19.   So currently in the repo solid-rest has your changes commented out and the old stuff there.  Could you maybe look at it and see if I implemented your changes wrong. Sorry for the mess.

**Comment by CxRes** [comment]
It is strange that tests seem to fail here and that errors are `ENOENT` (test files are not getting created?).  All the tests pass on my computer albeit it is the older version. I'll try cloning the present version and check when I have some free time:

Again try changing:  https://github.com/jeff-zucker/solid-rest/blob/eb2d5cb8fc094378d5be159caa3d1427975b7b60/tests/all.js#L29 with 
```js
else if(scheme==="file:") scheme = libUrl.pathToFileURL(process.cwd())
```

and

https://github.com/jeff-zucker/solid-rest/blob/eb2d5cb8fc094378d5be159caa3d1427975b7b60/tests/all.js#L78 with
```js
  try {res=await PUT(libUrl.pathToFileURL(process.cwd())+"/test-folder/dummy.txt") }catch{}
```

**Comment by CxRes** [comment]
Ok, the changes you have made are significant enough that I get the same 4/19 pass when I put in my changes.

Strangely, without my changes I am getting 19/19 pass, while you are reporting 17/19 pass (through the path-url conversion logic is definitely wrong i.e. the file urls mix back and forward slashes)!

**Comment by CxRes** [comment]
I figured the cause why my changes are not working:

All the changes till this point are correct except I have missed out changes at one place. The path calculations in `makeContainer` function (file.js) are being done the old way and the underlying folder is not created during the initial put. You have one of two options here:
1) (Suggested) remove the `makeContainer` function itself from the PUT logic in rest.js and use `outputFileSync` in lieu of `writeFileSync` in file.js.
2) Fix path calculations in `makeContainer` using node's inbuilt methods.

I have 19/19 tests passing, though the underlying paths are a mess and are only co-incidentally working (paths in tests should again be calculated using platform independently). Let me know if you want to fix it yourself or I'll can just make a new PR.

**Comment by jeff-zucker** [comment]
I can not figure how to get  makeContainers behave, everything else seems to work with your changes in tests/all.js and rest.js

**Comment by CxRes** [comment]
Try this:
```js
async makeContainers(pathname){
      const foldername = path.dirname(pathname)
      const [type, exists] = await this.getObjectType(foldername);
      if (!exists) {
        try {
          fs.mkdirpSync(foldername);
          return Promise.resolve([201])
        }
        catch{
          return Promise.resolve([500])
        }
      }
      return Promise.resolve([200])
}
```

**Comment by CxRes** [comment]
Travis is happy now!!!!!

**Comment by jeff-zucker** [comment]
If Travis is happy, I am happy.  Thanks for all your work.  I had put path.dirname in there but must have missed something else.

**Comment by jeff-zucker** [comment]
In honor of this achievement, I am bumping from 1.0.x to 1.2.x.  @CxRes how would you like to be listed in the acknowledgements/contributor - full name or nick?

**Comment by CxRes** [comment]
Nickname is fine, Thanks!

**Pull request merged**
